// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, fetcher, server;

  express = require('express');

  fetcher = require('./fetcher');

  app = express();

  app.get('/query', function(req, res) {
    if ((req.query.id != null) && (req.query.password != null)) {
      return fetcher.run(req.query.id, req.query.password, res);
    } else {
      return res.send('invalid');
    }
  });

  app.use(express["static"]('wwwfiles'));

  server = app.listen(8000, function() {
    return console.log("Listening on " + (server.address().address) + ":" + (server.address().port));
  });

}).call(this);
