// Generated by CoffeeScript 1.8.0
(function() {
  var cheerio, fetch, option, parse, run;

  cheerio = require('cheerio');

  run = function(id, password, res) {
    return option(id, password, res);
  };

  option = function(id, password, res) {
    var listOptions, listQueryString, listUrl, loginOptions, loginPostData, loginQueryString, loginUrl;
    loginUrl = 'https://myportal.sutd.edu.sg/psp/EPPRD/';
    loginQueryString = {
      cmd: "login",
      languageCd: "ENG"
    };
    loginPostData = {
      timezoneOffset: "-480",
      userid: id,
      pwd: password
    };
    loginOptions = {
      url: loginUrl,
      method: "POST",
      qs: loginQueryString,
      form: loginPostData
    };
    listUrl = 'https://sams.sutd.edu.sg/psc/CSPRD/EMPLOYEE/HRMS/c/SA_LEARNER_SERVICES.SSR_SSENRL_LIST.GBL';
    listQueryString = {
      Page: "SSR_SSENRL_LIST",
      Action: "A",
      EMPLID: id,
      TargetFrameName: "None"
    };
    listOptions = {
      url: listUrl,
      qs: listQueryString
    };
    return fetch(loginOptions, listOptions, res);
  };

  fetch = function(loginOptions, listOptions, res) {
    var request;
    request = require('request').defaults({
      jar: require('request').jar(),
      strictSSL: false,
      gzip: true,
      followAllRedirects: true,
      headers: {
        "User-Agent": "Node.js/Express"
      }
    });
    return request(loginOptions, function(loginError, loginResponse, loginBody) {
      if (loginError) {
        return console.log(loginError);
      } else {
        return request(listOptions, function(listError, listResponse, listBody) {
          if (listError) {
            return console.log(listError);
          } else {
            return parse(listBody, res);
          }
        });
      }
    });
  };

  parse = function(body, res) {
    var $, courses;
    $ = cheerio.load(body);
    courses = [];
    $('table.PSGROUPBOXWBO').each(function(index, value) {
      var course, i, lesson, nodes, _i, _ref;
      if (index !== 0) {
        course = {
          "name": $(this).find('td.PAGROUPDIVIDER').text()
        };
        nodes = [];
        $(this).find('span.PSEDITBOX_DISPONLY, span.PSLONGEDITBOX').each(function(index, value) {
          var node;
          node = $(this).text();
          if (node.length > 1) {
            return nodes.push(node);
          }
        });
        course['status'] = nodes.shift();
        course['units'] = nodes.shift();
        course['grading'] = nodes.shift();
        course['classNumber'] = nodes.shift();
        course['component'] = nodes.shift();
        course['lessons'] = [];
        for (i = _i = 0, _ref = nodes.length; _i < _ref; i = _i += 4) {
          lesson = {
            time: nodes[i],
            room: nodes[i + 1],
            instructor: nodes[i + 2],
            date: nodes[i + 3]
          };
          course['lessons'].push(lesson);
        }
        return courses.push(course);
      }
    });
    return res.json(courses);
  };

  exports.run = run;

}).call(this);
