// Generated by CoffeeScript 1.8.0
(function() {
  var parse;

  $(function() {
    $(document).keydown(function(event) {
      var enterKeyCode;
      enterKeyCode = 13;
      if (event.keyCode === enterKeyCode) {
        return $('#loginButton').click();
      }
    });
    return $('#loginButton').click(function() {
      console.log('clicked');
      '$.ajax\n	type: \'GET\'\n	url: \'query\'\n	data: $(\'#loginForm\').serialize()\n	success: parse';
      return parse(JSON.parse(localStorage.getItem('courses')));
    });
  });

  parse = function(body) {
    var calendar, course, day, lesson, month, year, _i, _j, _k, _l, _len, _len1, _m, _ref, _ref1;
    calendar = {};
    'month = {}\nmonths = {}\nfor day in [1..31]\n	day = String(day)\n	if day.length == 1\n		day = \'0\' + day\n	month[day] = []\n	console.log month\n\nfor monthIndex in [1..12]\n	monthIndex = String(monthIndex)\n	if monthIndex.length == 1\n		monthIndex = \'0\' + monthIndex\n	months[monthIndex] = month';
    for (year = _i = 2014; _i <= 2014; year = ++_i) {
      calendar[year] = {};
      for (month = _j = 9; _j <= 12; month = ++_j) {
        month = String(month);
        if (month.length === 1) {
          month = '0' + month;
        }
        calendar[year][month] = {};
        for (day = _k = 1; _k <= 31; day = ++_k) {
          day = String(day);
          if (day.length === 1) {
            day = '0' + day;
          }
          calendar[year][month][day] = [];
        }
      }
    }
    for (_l = 0, _len = body.length; _l < _len; _l++) {
      course = body[_l];
      _ref = course.lessons;
      for (_m = 0, _len1 = _ref.length; _m < _len1; _m++) {
        lesson = _ref[_m];
        _ref1 = lesson.date.split('/'), day = _ref1[0], month = _ref1[1], year = _ref1[2];
        lesson['name'] = course.name;
        calendar[year][month][day].push(lesson);
      }
    }
    console.log(calendar);
    return localStorage.setItem('calendar', JSON.stringify(calendar));
  };

}).call(this);
